import { defineCollection } from 'astro:content';
import { z } from 'astro/zod';
import { glob } from 'astro/loaders';

const articles = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/articles' }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    cluster: z.enum([
      'personality',
      'relationships',
      'astrology-guides',
      'ai-astrology',
      'zodiac',
      'insights',
    ]),
    topic: z.string(),
    audience: z.enum([
      'beginner',
      'enthusiast',
      'curious',
      'dating',
      'general',
      'spiritual_seeker',
    ]).default('general'),
    searchIntent: z.enum([
      'informational',
      'navigational',
      'commercial',
      'transactional',
    ]).default('informational'),
    acquisitionIntent: z.enum([
      'awareness',
      'consideration',
      'conversion',
      'retention',
    ]).default('awareness'),
    contentType: z.enum([
      'guide',
      'hub',
      'explainer',
      'faq',
      'analysis',
    ]).default('guide'),
    zodiacSign: z.enum([
      'aries',
      'taurus',
      'gemini',
      'cancer',
      'leo',
      'virgo',
      'libra',
      'scorpio',
      'sagittarius',
      'capricorn',
      'aquarius',
      'pisces',
    ]).optional(),
    relatedSigns: z.array(z.enum([
      'aries',
      'taurus',
      'gemini',
      'cancer',
      'leo',
      'virgo',
      'libra',
      'scorpio',
      'sagittarius',
      'capricorn',
      'aquarius',
      'pisces',
    ])).default([]),
    relatedAppFeatures: z.array(z.string()).default([]),
    relatedFeature: z.string().optional(),
    relatedTool: z.string().optional(),
    relatedContent: z.array(z.string()).default([]),
    socialChannels: z.array(z.enum(['facebook', 'instagram', 'pinterest'])).default([]),
    socialReuseEligible: z.boolean().default(true),
    ctaType: z.enum([
      'personalized_insights',
      'birth_chart',
      'ask_ai',
      'compatibility',
      'explore_zodiac',
    ]).default('personalized_insights'),
    readingTime: z.string().default('4 min read'),
    image: z.string().optional(),
    ogImage: z.string().optional(),
    seoTitle: z.string().optional(),
    seoDescription: z.string().optional(),
    publishedDate: z.string(),
    updatedDate: z.string().optional(),
    draft: z.boolean().default(false),
  }),
});

export const collections = { articles };
